Завершение вёрстки всех компонентов
htmlacademy-htmlcss/1818635-gllacy-32 pull request #11
Opened 2021-11-09 09:43 UTC by olgazubchenok

2021-11-10 15:03 UTC, Dima-Dim requested changes
img/icon/radio-off-hover.svg, img/icon/radio-on-hover.svg и т.п. для чего там svg, там простые фигуры которые делются на css.
Чекбокс, да, на css не сделать, но его состояния меняются через css, достаточно одного svg.

Поиск, Вход, Пусто и т.п. отображаться "выпадашки" должны при наведении на них.

2021-11-12 08:26 UTC, olgazubchenok commented on index.html
> +                            <svg class="navigation-icon" aria-hidden="true" focusable="false" width="18" height="18"
Когда корзина заполнена иконка закрашивается)

2021-11-12 10:21 UTC, olgazubchenok commented on index.html
> +                            <svg class="navigation-icon" aria-hidden="true" focusable="false" width="18" height="18"
в активном состоянии она закрашена

2021-11-13 13:40 UTC, Dima-Dim reviewed
Хорошо бы что бы можно было мышкой попасть в появляющиеся при наведении блоки, типа Поиска, сейчас я это сделать не успеваю :) они исчезают.

2021-11-13 13:40 UTC, merged